name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secret.DOCKER_USERNAME }} --password-stdin


      
    - name: Build the Docker image
      run: |
      IMAGE_TAG=fabutnm/test:${{ github.sha }}
      docker build -t howepu/dock:${{ github.sha }} .
      docker push howepu/dock:${{ github.sha }}
